sudo: required
services:
    - docker

before_install:
    - docker build -t mohit35/docker-react-demo -f Dockerfile.dev .

script:
    - docker run mohit35/docker-react-demo npm run test -- --coverage